<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Actor extends \App\Entity\Actor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'birthName', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'nickName', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'birth', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'born', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'height', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'imageShares', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'biography'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'birthName', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'nickName', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'birth', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'born', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'height', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'imageShares', '' . "\0" . 'App\\Entity\\Actor' . "\0" . 'biography'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Actor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthName', []);

        return parent::getBirthName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthName(?string $birthName): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthName', [$birthName]);

        return parent::setBirthName($birthName);
    }

    /**
     * {@inheritDoc}
     */
    public function getNickName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickName', []);

        return parent::getNickName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNickName(string $nickName): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickName', [$nickName]);

        return parent::setNickName($nickName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(?int $gender): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirth(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirth', []);

        return parent::getBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirth(?\DateTimeInterface $birth): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirth', [$birth]);

        return parent::setBirth($birth);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorn', []);

        return parent::getBorn();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorn(string $born): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorn', [$born]);

        return parent::setBorn($born);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(string $country): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', []);

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight(string $height): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', [$height]);

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageShares(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageShares', []);

        return parent::getImageShares();
    }

    /**
     * {@inheritDoc}
     */
    public function addImageShare(\App\Entity\ImageShare $imageShare): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImageShare', [$imageShare]);

        return parent::addImageShare($imageShare);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImageShare(\App\Entity\ImageShare $imageShare): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImageShare', [$imageShare]);

        return parent::removeImageShare($imageShare);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiography(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiography', []);

        return parent::getBiography();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiography(?string $biography): \App\Entity\Actor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiography', [$biography]);

        return parent::setBiography($biography);
    }

}
