<?php

namespace Container8kcxrgi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OSPAcaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oSPAca_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oSPAca_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detail' => ['privates', '.errored..service_locator.oSPAca_.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.oSPAca_": it references class "App\\Entity\\Contact" but no such service exists.'],
        ], [
            'detail' => 'App\\Entity\\Contact',
        ]);
    }
}
