<?php

namespace Container8kcxrgi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SOHAWjMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sOHAWjM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sOHAWjM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actors' => ['privates', 'App\\Repository\\ActorRepository', 'getActorRepositoryService', true],
        ], [
            'actors' => 'App\\Repository\\ActorRepository',
        ]);
    }
}
