<?php

namespace Container8kcxrgi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oSPAca_.App\Entity\Contact' shared service.
     *
     * @return \App\Entity\Contact
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oSPAca_": it references class "App\\Entity\\Contact" but no such service exists.');
    }
}
