<?php

namespace Container8kcxrgi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditActorFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EditActorFormType' shared autowired service.
     *
     * @return \App\Form\EditActorFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EditActorFormType.php';

        return $container->privates['App\\Form\\EditActorFormType'] = new \App\Form\EditActorFormType();
    }
}
