<?php

namespace ContainerMtlyTPG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BDDYr2GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bDDYr2G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bDDYr2G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imageShares' => ['privates', 'App\\Repository\\ImageShareRepository', 'getImageShareRepositoryService', true],
        ], [
            'imageShares' => 'App\\Repository\\ImageShareRepository',
        ]);
    }
}
