<?php

namespace ContainerMtlyTPG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6lQN65V.App\Entity\Actor' shared service.
     *
     * @return \App\Entity\Actor
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6lQN65V": it references class "App\\Entity\\Actor" but no such service exists.');
    }
}
